stages:
- name: Build
  when:
    branch: master
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: personal-website:latest
- name: Deploy
  when:
    branch: master
  steps:
  - applyYamlConfig:
      path: ./deployment.yml