stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: personal-website:latest
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yml