language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
install:
- yarn install
script:
- yarn run generate
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: cjcE3D4KhCWV0zWP2fkN7iS1Ifo4lW8g5PsRG8mV1vwp1rr/uUz1CP6Fa/iuW2Hm+a/DGdeH6dXDFgmgnv40E9i1EqyLt16RjHxsJxOWiTl7tzPBAEDP2AnUtyxOnFT7fszz8qQkXF74zzr61nTm/KXwEHmZE/pO+/Aagr1Y8YP2LKF57RMO3wX+FvHMMLWXK5XcCmOsz4nLVRJCpZftqOqrfrRBfg0tIy9qTKl6GPPr6gTWGKDnqUDft2Rdkazr73gD3LPuYQ0ijRNAJLwwi2AIoT4+yloZqudbraAk3+ZddfkzyEdxTEG/XqMOBR/dCOHR3EZ3+Nk/LjKGmLParBSoZs5k+q7UftugkV9VoiSYhK+YNYAM9ITStkwiFB7xbrSjVsZ7jXAjQczf2pw/B3ma2ur8XBrPNVXXKRxaBbYiWGlJJralcfa+bTzcfhVrIhtcV6rqknLIZEYxIFxFz3JKG9RciBy/NkPGiFNidK45QbnFs10PR6HpbQPGyQb7Nfmduk8OalkHw5GCLhahYIjG5s8m3/CUpZPX7h5KEmHiwoU9oywuClYpNxLxb2KssBRKqs2kmExlKXdhVO6WEaiXCXIMVkG8jppyo5pS6RK/xe/pcFH06SvSmN+1i0nYI65XVM6PBb8FMYn8HVopp0XnaN6He1HJOMniARcuqOI=
