apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: matthias-entry-route
  namespace: website
spec:
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  hosts:
  - matthias.it-dudes.de
  http:
  - match:
    - uri:
        prefix: "/"
    rewrite:
      authority: matthias-serving.webiste.it-dudes.de
    route:
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
        weight: 100
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: matthias-serving
  namespace: website
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "100"
    spec:
      containers:
      - image: ${CICD_IMAGE}:latest
        readinessProbe:
          httpGet:
            path: /
          initialDelaySeconds: 0
          periodSeconds: 3