apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal
  namespace: website
  labels:
    app: personal
spec:
  selector:
    matchLabels:
      app: personal
  template:
    metadata:
      labels:
        app: personal
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: personal
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: website
  name: personal-service
spec:
  selector:
    app: personal
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: peronal
  namespace: website
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - matthias.it-dudes.de
    secretName: personal-crt
  rules:
  - host: matthias.it-dudes.de
    http:
      paths:
      - path: /
        backend:
          serviceName: personal-service
          servicePort: 80