name: Release

on:
  pull_request:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-version
          cache: 'npm'
      - run: npm install -g firebase-tools
      - run: npm ci
      - run: npm run build
        env:
          NITRO_PRESET: firebase
      - name: Manipulate build for firebase
        run: |
          jq '.main |= "server/index.mjs"' .output/server/package.json > .output/package.json
          rm -f .output/server/package.json
          mv .output/server/node_modules .output/.
      - name: Prepare Google Application Credentials
        shell: bash
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HMH_SIDEPROJECTS }}" > "google-application-credentials.json"
      - run: firebase deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm google-application-credentials.json
